# Generated by Django 4.0.4 on 2022-11-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('setial_no', models.CharField(max_length=255, unique=True)),
                ('devise_id', models.CharField(max_length=255, unique=True)),
                ('chipset_no', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('time_of_sale', models.TimeField()),
                ('warrenty', models.CharField(max_length=255)),
                ('amount_paid', models.BigIntegerField()),
            ],
        ),
    ]
