# Generated by Django 4.1.9 on 2023-05-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviseapis',
            name='crop_type',
            field=models.CharField(max_length=255),
        ),
    ]
