# Generated by Django 4.0.4 on 2022-12-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviselocation',
            name='latitude',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviselocation',
            name='longitude',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviselocation',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='devise',
            name='warrenty',
            field=models.DateField(),
        ),
    ]
