# Generated by Django 4.0.4 on 2022-12-06 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devise',
            name='balance_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
