# Generated by Django 4.0.4 on 2022-12-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0002_devise_balance_amount_devise_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devise',
            name='warrenty',
            field=models.DateField(max_length=255),
        ),
    ]
