# Generated by Django 4.0.4 on 2022-12-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0002_deviselocation_latitude_deviselocation_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviselocation',
            old_name='decise',
            new_name='devise',
        ),
    ]
