# Generated by Django 4.0.4 on 2023-01-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0008_alter_deviselocation_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='devise',
            name='land',
            field=models.FloatField(default=0.0),
        ),
    ]
