# Generated by Django 4.0.4 on 2023-02-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0009_devise_land'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.FloatField(default=0.0)),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriapp.columnname')),
                ('parameter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriapp.deviseapis', unique=True)),
            ],
        ),
    ]
