# Generated by Django 4.0.4 on 2023-02-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0010_columnname_columndata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columndata',
            old_name='parameter_id',
            new_name='api',
        ),
        migrations.RenameField(
            model_name='columndata',
            old_name='field_id',
            new_name='field',
        ),
    ]
